version: "3.9"

services:
  inventory-service:
    build: ./inventory-service
    ports:
      - "5002:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    depends_on:
      - mysql
    networks:
      - backend

  order-service:
    build: ./order-service
    ports:
      - "5003:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    depends_on:
      - mysql
    networks:
      - backend

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: inventory_db
      MYSQL_USER: flask_user
      MYSQL_PASSWORD: flask_password
    ports:
      - "3306:3306"
    networks:
      - backend
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

networks:
  backend:
